# ⚠️  LEGACY: Use root-level docker-compose.yml and ./start-services.sh instead
# This file is kept for backward compatibility only
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - BACKEND_URL=http://rag-api:8000